FROM node:16 AS build
WORKDIR /app
COPY package* yarn.lock ./
RUN yarn install --pure-lockfile
COPY . ./
RUN yarn run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html